mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.static import serve

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    
    url(r'^photologue/', include('photologue.urls')),
    url(r'^$', TemplateView.as_view(template_name="homepage.html"), name='homepage'),
    
    # 处理 media 信息，用于图片获取
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    
    #url(r'^$', RedirectView.as_view(url='/account/index/', query_string=True)),
    #url(r'^$', RedirectView.as_view(url='/login/', query_string=True)),

] #+ static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/photologue/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .views import PhotoListView, PhotoDetailView, \
    PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView


app_name = 'photologue'
urlpatterns = [

    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
        PhotoDateDetailView.as_view(month_format='%m'),
        name='photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
        PhotoDayArchiveView.as_view(month_format='%m'),
        name='photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
        PhotoMonthArchiveView.as_view(month_format='%m'),
        name='photo-archive-month'),
    url(r'^photo/(?P<year>\d{4})/$',
        PhotoYearArchiveView.as_view(),
        name='pl-photo-archive-year'),
    url(r'^photo/$',
        PhotoArchiveIndexView.as_view(),
        name='pl-photo-archive'),
 
    url(r'^photo/(?P<slug>[\-\d\w]+)/$',
        PhotoDetailView.as_view(),
        name='pl-photo'),
    url(r'^photolist/$',
        PhotoListView.as_view(),
        name='photo-list'),
]

mysite/photologue/forms.py
import zipfile
from zipfile import BadZipFile
import logging
import os
from io import BytesIO

from PIL import Image


from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
#from django.contrib.sites.models import Site
from django.conf import settings
from django.utils.encoding import force_text
from django.template.defaultfilters import slugify
from django.core.files.base import ContentFile
#from django.forms.widgets import HiddenInput
from .models import  Photo

logger = logging.getLogger('photologue.forms')

# 供 admin.py 中使用
class UploadZipForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['zip_file', 'title']
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }
        
    
    def clean_zip_file(self):
        """Open the zip file a first time, to check that it is a valid zip archive.
        We'll open it again in a moment, so we have some duplication, but let's focus
        on keeping the code easier to read!
        """
        zip_file = self.cleaned_data['zip_file']
        try:
            zip = zipfile.ZipFile(zip_file)
        except BadZipFile as e:
            raise forms.ValidationError(str(e))
        bad_file = zip.testzip()
        if bad_file:
            zip.close()
            raise forms.ValidationError('"%s" in the .zip archive is corrupt.' % bad_file)
        zip.close()  # Close file in all cases.
        return zip_file

    def clean_title(self):
        #title = self.cleaned_data.get('title', None)
        title = self.cleaned_data.get('zip_file', None)
        title = title.name 
        if title and Photo.objects.filter(title=title).exists():
            raise forms.ValidationError(_('A photo with that title already exists.'))
        return title

    def clean(self):
        cleaned_data = super().clean()
        if not self['title'].errors:
            # If there's already an error in the title, no need to add another error related to the same field.
            # 如果标题中已经有错误，则无需添加与同一字段相关的其他错误。
            if not cleaned_data.get('title', None) :
                raise forms.ValidationError(
                    _('Select an existing gallery, or enter a title for a new photo.'))
        return cleaned_data

    def save(self, request=None, zip_file=None):
        if not zip_file:
            zip_file = self.cleaned_data['zip_file']
        zip = zipfile.ZipFile(zip_file)
        count = 1
        
        
        title = self.clean_title()
        
        for filename in sorted(zip.namelist()):

            logger.debug('Reading file "{}".'.format(filename))

            if filename.startswith('__') or filename.startswith('.'):
                logger.debug('Ignoring file "{}".'.format(filename))
                continue

            if os.path.dirname(filename):
                logger.warning('Ignoring file "{}" as it is in a subfolder; all images should be in the top '
                               'folder of the zip.'.format(filename))
                if request:
                    messages.warning(request,
                                     _('Ignoring file "{filename}" as it is in a subfolder; all images should '
                                       'be in the top folder of the zip.').format(filename=filename),
                                     fail_silently=True)
                continue

            data = zip.read(filename)

            if not len(data):
                logger.debug('File "{}" is empty.'.format(filename))
                continue

            
            
            # A photo might already exist with the same slug. 一张照片可能已经存在与相同的弹头。
            # So it's somewhat inefficient, 所以效率有点低，
            # but we loop until we find a slug that's available. 但我们会一直循环直到找到一个可用的弹头
            while True:
                photo_title = ' '.join([title, str(count)])
                slug = slugify(photo_title) # 全部转化成小写字母,空格部分替换成短横线 -  print(slugify('The song of ice and fire ')) # the-song-of-ice-and-fire
                if Photo.objects.filter(slug=slug).exists(): # 判断数据库的记录是否存在
                    count += 1
                    continue
                break

            photo = Photo(title=title,
                          slug=slug)

            # Basic check that we have a valid image. 基本检查我们有一个有效的图像。
            try:
                file = BytesIO(data)
                opened = Image.open(file)
                opened.verify()
            except Exception:
                # Pillow doesn't recognize it as an image.
                # If a "bad" file is found we just skip it.
                # But we do flag this both in the logs and to the user.
                logger.error('Could not process file "{}" in the .zip archive.'.format(
                    filename))
                if request:
                    messages.warning(request,
                                     _('Could not process file "{0}" in the .zip archive.').format(
                                         filename),
                                     fail_silently=True)
                continue

            contentfile = ContentFile(data)
            photo.image.save(filename, contentfile)
            photo.save()
            
            count += 1

        zip.close()

mysite/photologue/views.py
from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, \
    YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Photo


# Photo views.

class PhotoListView(ListView):
    queryset = Photo.objects.all()
    paginate_by = 20


class PhotoDetailView(DetailView):
    pass
    #queryset = Photo.objects.on_site().is_public()


class PhotoDateView:
    #queryset = Photo.objects.on_site().is_public()
    #date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True

mysite/photologue/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Bootstrap -->
		<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<link href="/static/css/screen.css" rel="stylesheet" media="screen">
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script src="{{ STATIC_URL }}js/html5shiv.min.js"></script>
	      <script src="{{ STATIC_URL }}js/respond.min.js"></script>
	    <![endif]-->
    </head>
    <body>
        <!-- Navigation -->
		<nav class="navbar navbar-default" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" href="/">Photologue project - {{ user.username }}</a>
		  </div>
		
		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse navbar-ex1-collapse">
		    <ul class="nav navbar-nav">
			    <li class="home"><a href="/">Home</a></li>
			    {% if user in operators %}
            
            	{% endif %}
            	<li><a href="/admin/">管理</a></li>

			    
			    <li class="photos dropdown">
					<a data-target="#" href="" class="dropdown-toggle" data-toggle="dropdown">
			            Photo views<b class="caret"></b>
			        </a>
					<ul class="dropdown-menu">
						<li class="sub-page"><a href="{% url 'photologue:pl-photo-archive' %}">Date views</a></li>
						<li class="sub-page"><a href="{% url 'photologue:photo-list' %}">List views</a></li>
					</ul>
				</li>

				<li> <!-- 搜索框 如何居右? {# action= {% url 'search' %} #}-->
              		<form method="post" action="" class="navbar-form navbar-left" rol="search">
                		{% csrf_token %}
                		<div class="form-group" >
                  			<input name='q' type="text" class="form-control" placeholder="请输入关键词" />
                		</div>
                		<button type="submit" class="btn btn-default"><i class="fa fa-search"></i> 搜 索</button>
            		</form>
           		</li>
		    </ul>
		  </div><!-- /.navbar-collapse -->
		</nav>
    	<div class="container">
        	{% block content %}{% endblock %}
        </div>
        <script src="/static/js/jquery.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
		<script src="/static/js/project.js"></script>
    </body>
</html>

mysite/photologue/templates/homepage.html
{% extends 'base.html' %}

{% block title %}Photologue example project{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
			  <h1>Welcome to the Photologue example project</h1>
			</div>
			<p>This is a quick demo of the Photologue application - just click on
			the menu options above.</p>
			<p>It uses the built-in <a href="http://getbootstrap.com/">Bootstrap</a>-compatible
			templates that you can use to get you quickly up and running, or completely
			replace with your own templates.</p>
		</div>
	</div>
{% endblock %}